from __future__ import annotations

from pathlib import Path

import highdicom as hd
import nibabel as nib
import numpy as np
from pydicom.sr.codedict import codes


class DicomSegError(RuntimeError):
    """Raised when DICOM SEG creation fails."""


def find_ct_dicom_files(
    dicom_directory: str | Path,
) -> list[Path]:
    """
    Find exactly one CT DICOM series.

    Returns the DICOM files in GDCM series order.
    """

    directory = Path(
        dicom_directory
    )

    if not directory.exists():
        raise DicomSegError(
            f"DICOM directory does not exist: {directory}"
        )

    if not directory.is_dir():
        raise DicomSegError(
            f"Expected a DICOM directory: {directory}"
        )

   

    # Use SimpleITK/GDCM discovery through
    # the existing DICOM module.
    from app.io.dicom import (
        find_dicom_series,
    )

    series = find_dicom_series(
        directory
    )

    ct_series = [
        item
        for item in series
        if item["modality"].upper() == "CT"
    ]

    if not ct_series:
        raise DicomSegError(
            "No CT DICOM series found."
        )

    if len(ct_series) > 1:
        descriptions = [
            {
                "uid": item["series_uid"],
                "description": item["description"],
                "files": item["file_count"],
            }
            for item in ct_series
        ]

        raise DicomSegError(
            "Multiple CT series found. "
            "Please provide one CT series at a time. "
            f"Found: {descriptions}"
        )

    files = ct_series[0]["files"]

    return [
        Path(file)
        for file in files
    ]


def create_dicom_seg(
    dicom_directory: str | Path,
    segmentation_path: str | Path,
    output_path: str | Path,
) -> dict:
    """
    Create a binary DICOM SEG object for the spleen.

    Parameters
    ----------
    dicom_directory:
        Directory containing one CT DICOM series.

    segmentation_path:
        NIfTI segmentation generated by MedSegOps.

    output_path:
        Destination DICOM SEG file.

    Returns
    -------
    dict
        Information about the generated DICOM SEG.
    """

    dicom_directory = Path(
        dicom_directory
    )

    segmentation_path = Path(
        segmentation_path
    )

    output_path = Path(
        output_path
    )

    if not segmentation_path.exists():
        raise DicomSegError(
            "Segmentation file does not exist: "
            f"{segmentation_path}"
        )

    output_path.parent.mkdir(
        parents=True,
        exist_ok=True,
    )

    print(
        "Loading DICOM source images..."
    )

    source_files = find_ct_dicom_files(
        dicom_directory
    )

    if not source_files:
        raise DicomSegError(
            "No DICOM CT files found."
        )

    print(
        f"Found {len(source_files)} "
        "DICOM CT files."
    )

    # --------------------------------------------------------
    # Read source DICOM images
    # --------------------------------------------------------

    source_images = [
        hd.imread(
            str(path)
        )
        for path in source_files
    ]

    # --------------------------------------------------------
    # IMPORTANT:
    # Sort source images spatially.
    # --------------------------------------------------------

    source_images = (
        hd.spatial.sort_datasets(
            source_images
        )
    )

    print(
        "DICOM source images sorted spatially."
    )

    # --------------------------------------------------------
    # Build source volume
    # --------------------------------------------------------

    source_volume = (
        hd.get_volume_from_series(
            source_images
        )
    )

    print(
        "Source DICOM volume:"
    )

    print(
        "  shape:",
        source_volume.spatial_shape,
    )

    print(
        "  spacing:",
        source_volume.spacing,
    )

    print(
        "  frame of reference:",
        source_volume.frame_of_reference_uid,
    )

    # --------------------------------------------------------
    # Load segmentation NIfTI
    # --------------------------------------------------------

    print(
        "Loading segmentation NIfTI..."
    )

    segmentation_nifti = nib.load(
        str(segmentation_path)
    )

    print(
        "Segmentation NIfTI shape:",
        segmentation_nifti.shape,
    )

    # --------------------------------------------------------
    # Convert NIfTI to highdicom Volume.
    #
    # highdicom handles the NIfTI RAS -> DICOM LPS
    # convention conversion.
    # --------------------------------------------------------

    mask_volume = (
        hd.Volume.from_nibabel(
            segmentation_nifti,
            coordinate_system=(
                hd.CoordinateSystemNames.PATIENT
            ),
            frame_of_reference_uid=(
                source_volume.frame_of_reference_uid
            ),
        )
    )

    print(
        "Mask volume geometry:"
    )

    print(
        "  shape:",
        mask_volume.spatial_shape,
    )

    print(
        "  spacing:",
        mask_volume.spacing,
    )

    # --------------------------------------------------------
    # Check geometry.
    #
    # Ideally the segmentation generated by our existing
    # Invertd/SaveImaged pipeline already has the source
    # DICOM geometry.
    # --------------------------------------------------------

    if not mask_volume.geometry_equal(
        source_volume,
        tol=1e-3,
    ):

        print(
            "Mask geometry differs from "
            "DICOM source geometry."
        )

        print(
            "Attempting geometry matching "
            "without resampling..."
        )

        try:

            mask_volume = (
                mask_volume.match_geometry(
                    source_volume
                )
            )

        except RuntimeError as error:

            raise DicomSegError(
                "The segmentation geometry does not "
                "match the source DICOM geometry and "
                "cannot be corrected using only "
                "permutations/flips/cropping/padding. "
                "This requires explicit resampling. "
                f"Details: {error}"
            ) from error

    print(
        "Mask geometry matches "
        "DICOM source geometry."
    )

    # --------------------------------------------------------
    # Convert mask to binary uint8.
    # --------------------------------------------------------

    mask_array = np.asarray(
        mask_volume.array
    )

    if mask_array.ndim != 3:
        raise DicomSegError(
            "Expected a 3D segmentation mask, "
            f"got shape {mask_array.shape}"
        )

    binary_mask = (
        mask_array > 0
    ).astype(
        np.uint8
    )

    print(
        "Binary mask shape:",
        binary_mask.shape,
    )

    print(
        "Spleen voxels:",
        int(
            np.count_nonzero(
                binary_mask
            )
        ),
    )

    # --------------------------------------------------------
    # Make sure the mask volume has the exact geometry of
    # the source volume.
    # --------------------------------------------------------

    mask_volume = (
        source_volume.with_array(
            binary_mask
        )
    )

    # --------------------------------------------------------
    # Algorithm identification
    # --------------------------------------------------------

    algorithm_identification = (
        hd.AlgorithmIdentificationSequence(
            name="MedSegOps-Spleen",
            version="0.3.0",
            family=(
                codes.cid7162.ArtificialIntelligence
            ),
        )
    )

    # --------------------------------------------------------
    # Segment description
    # --------------------------------------------------------

    spleen_description = (
        hd.seg.SegmentDescription(
            segment_number=1,
            segment_label="Spleen",
            segmented_property_category=(
                codes.SCT.AnatomicalStructure
            ),
            segmented_property_type=(
                codes.SCT.Spleen
            ),
            algorithm_type=(
                hd.seg.SegmentAlgorithmTypeValues.AUTOMATIC
            ),
            algorithm_identification=(
                algorithm_identification
            ),
            tracking_uid=hd.UID(),
            tracking_id="MedSegOps-Spleen",
        )
    )

    # --------------------------------------------------------
    # Create DICOM SEG
    # --------------------------------------------------------

    print(
        "Creating DICOM SEG..."
    )

    seg = hd.seg.Segmentation(
        source_images=source_images,
        pixel_array=mask_volume,
        segmentation_type=(
            hd.seg.SegmentationTypeValues.BINARY
        ),
        segment_descriptions=[
            spleen_description
        ],
        series_instance_uid=hd.UID(),
        series_number=900,
        sop_instance_uid=hd.UID(),
        instance_number=1,
        manufacturer="MedSegOps",
        manufacturer_model_name=(
            "MedSegOps Spleen Segmentation"
        ),
        software_versions="0.3.0",
        device_serial_number="MEDSEGOPS001",
        series_description=(
            "MedSegOps Spleen Segmentation"
        ),
    )

    # --------------------------------------------------------
    # Save
    # --------------------------------------------------------

    seg.save_as(
        str(output_path)
    )

    print(
        "DICOM SEG saved:"
    )

    print(
        output_path
    )

    return {
        "output_path": str(
            output_path
        ),
        "source_file_count": len(
            source_images
        ),
        "mask_shape": [
            int(value)
            for value in binary_mask.shape
        ],
        "spleen_voxels": int(
            np.count_nonzero(
                binary_mask
            )
        ),
        "segment_label": "Spleen",
        "segment_number": 1,
        "segmentation_type": "BINARY",
    }