name: MedSegOps CD

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:

  publish:
    name: Build and Publish Docker Image
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          lfs: true

      - name: Ensure Git LFS is available
        run: |
          git lfs version
          git lfs install
          git lfs pull

      - name: Verify model artifact
        run: |
          test -f models/monai/model.pt

          SIZE=$(stat -c%s models/monai/model.pt)

          if [ "$SIZE" -lt 1000000 ]; then
            echo "ERROR: model.pt is not the actual model binary."
            exit 1
          fi

          echo "Model size:"
          ls -lh models/monai/model.pt

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v7
        with:
          context: .
          push: true
          tags: |
            ${{ steps.meta.outputs.tags }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
          labels: ${{ steps.meta.outputs.labels }}